### ISSUE TITLE
Paradenszenario in rlgym nachbauen

### ISSUE THREAD

**Issue by TheImus** [PG642/RoboLeague#4]

**Comment by hndm** [comment]
[RLGym](https://rlgym.github.io/) creates a gym environment wrapper for Rocket League. Currently the documentation is very sparse. 

You can only adjust the number of players and how they are controlled (in addition to non game play related variables). This leads to the problem that you cannot create custom trainings like Goalie training.
You can make a game by calling:
```python
def make(env_name: str,
         ep_len_minutes: float = None,
         game_speed: int = None,
         tick_skip: int = None,
         spawn_opponents: bool = None,
         random_resets: bool = None,
         team_size: int = None,
         terminal_conditions: List[object] = None,
         reward_fn: object = None,
         obs_builder: object = None,
         path_to_rl: str = None,
         use_injector: bool = False)
```
These are the parameters we can adjust. We can create custom observations, reward functions and terminal conditions. The last two variables `path_to_rl` and `use_injector` are only needed in case we want to run parallel instances.

RLGym could be interesting for evaluation since you can increase the game physics speed and run multiple instances of rocket league in parallel. We would have to compare the observation space of our implementation to the observation space available in RLGym to find out if they are compatible.

**Comment by hndm** [comment]
A few examples to make a gym environment would be 
```python
# default environment
env = rlgym.make("Default")
```

```python
# parallel environment (only once per process)
env = rlgym.make("Default",
                 path_to_rl="C:/Program Files/Epic Games/rocketleague/Binaries/Win64/rocketleague.exe",
                 use_injector=True)
```

```python
# 3 vs. 3 against RocketLeague Bots at normal speed
env = rlgym.make("Standard",
                 game_speed = 1,
                 spawn_opponents = True
```
